# Generated by Django 5.0.1 on 2025-11-17 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo_vaga_direito', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], help_text='Tipo de vaga que o apartamento tem direito (Carro ou Moto)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo_vaga', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_corunha.apartamento')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='la_corunha.vaga')),
            ],
        ),
    ]
