# Generated by Django 5.0.1 on 2025-11-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_corunha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
