# Generated by Django 5.0.1 on 2025-11-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_corunha', '0002_alter_apartamento_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='is_carro',
            field=models.BooleanField(default=False, help_text='True se for vaga de carro'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='is_moto',
            field=models.BooleanField(default=False, help_text='True se for vaga de moto'),
        ),
    ]
