# Generated by Django 5.0.1 on 2025-04-23 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('direito_vaga_dupla', models.BooleanField(default=False)),
                ('direito_duas_vagas_livres', models.BooleanField(default=False)),
                ('is_pne', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('subsolo', models.CharField(choices=[('Térreo', 'Térreo'), ('1º Subsolo', '1º Subsolo'), ('2º Subsolo', '2º Subsolo'), ('3º Subsolo', '3º Subsolo'), ('4º Subsolo', '4º Subsolo')], max_length=10)),
                ('tipo_vaga', models.CharField(choices=[('Simples', 'Simples'), ('Dupla', 'Dupla')], max_length=10)),
                ('is_pne', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvorada.apartamento')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvorada.vaga')),
            ],
        ),
    ]
