# Generated by Django 5.0.1 on 2025-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alvorada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamento',
            name='direito_duas_vagas_livres',
        ),
        migrations.RemoveField(
            model_name='apartamento',
            name='is_pne',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='is_pne',
        ),
        migrations.AlterField(
            model_name='vaga',
            name='subsolo',
            field=models.CharField(max_length=10),
        ),
    ]
