# Dockerfile
# 1) # 1) Imagem base com Python 3.12.7 (leve)
FROM python:3.12-slim
 
# 2) Evita buffering de saída (útil em logs)
ENV PYTHONUNBUFFERED=1

# 3) Diretório de trabalho dentro do container
WORKDIR /app

# 4) Copia apenas o manifesto de dependências
COPY requirements.txt ./

# 5) Instala as dependências sem cache
RUN pip install --no-cache-dir -r requirements.txt

# 6) Copia todo o código do projeto
COPY . .

# 7) Expõe a porta padrão do Django/Gunicorn
EXPOSE 8000

# 8) Comando padrão para iniciar o servidor 

# Comando para produção - Note que usamos o seu módulo 'setup' aqui
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "setup.wsgi:application"]

# Comando para desenvolvimento -
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
