version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE: postgres
      DATABASE_URL: postgres://django_user:django_pass@db:5432/django_db
    depends_on:
      - db

volumes:
  db_data: