version: "3.9"

services:
  web:
    image: sorteio_novo-web:latest
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/code/static
    networks:
      - LeituraSorteioNet
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sorteio.rule=Host(`sn.sorteionovo.com.br`)"
        - "traefik.http.routers.sorteio.entrypoints=websecure"
        - "traefik.http.routers.sorteio.tls=true"
        - "traefik.http.routers.sorteio.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.sorteio.loadbalancer.server.port=8000"
      restart_policy:
        condition: on-failure

volumes:
  static_volume:

networks:
  LeituraSorteioNet:
    external: true
