# Generated by Django 5.0.1 on 2025-11-17 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('bloco', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('bloco', models.CharField(blank=True, help_text='Bloco da vaga (opcional)', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buriti.apartamento')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buriti.vaga')),
            ],
        ),
    ]
