# Generated by Django 5.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmonia_class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='subsolo',
            new_name='localizacao',
        ),
    ]
