# Generated by Django 5.0.1 on 2025-06-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helborsorteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='pne',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='pne',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='numero',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='torre',
            field=models.CharField(db_index=True, default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='sorteio',
            name='data_sorteio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='torre',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AddIndex(
            model_name='apartamento',
            index=models.Index(fields=['torre', 'numero'], name='helborsorte_torre_cc6b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='apartamento',
            index=models.Index(fields=['pne'], name='helborsorte_pne_53625b_idx'),
        ),
        migrations.AddIndex(
            model_name='sorteio',
            index=models.Index(fields=['apartamento', 'vaga'], name='helborsorte_apartam_970b11_idx'),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['torre', 'numero'], name='helborsorte_torre_40fb50_idx'),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['pne'], name='helborsorte_pne_4b498f_idx'),
        ),
    ]
