# Generated by Django 5.0.1 on 2025-06-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helborsorteio', '0002_apartamento_pne_vaga_pne_alter_apartamento_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
