# Generated by Django 5.0.1 on 2025-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helborsorteio', '0003_alter_vaga_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
