# Generated by Django 5.0.1 on 2025-11-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_view', '0006_apartamento_is_pne_vaga_is_pne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='subsolo',
            field=models.CharField(choices=[('Térreo', 'Térreo'), ('1º Subsolo', '1º Subsolo'), ('2º Subsolo', '2º Subsolo'), ('3º Subsolo', '3º Subsolo'), ('4º Subsolo', '4º Subsolo')], max_length=15),
        ),
    ]
