# Generated by Django 5.0.1 on 2024-12-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gran_vitta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.CharField(max_length=30),
        ),
    ]
