# Generated by Django 5.0.1 on 2025-01-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passaros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='bloco',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='passaros.bloco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='passaros.bloco'),
        ),
    ]
