# Generated by Django 5.0.1 on 2025-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splendore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='numero',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='torre',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='sorteio',
            name='data_sorteio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='torre',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AddIndex(
            model_name='apartamento',
            index=models.Index(fields=['torre', 'numero'], name='splendore_a_torre_fefb92_idx'),
        ),
        migrations.AddIndex(
            model_name='sorteio',
            index=models.Index(fields=['apartamento', 'vaga'], name='splendore_s_apartam_b9c413_idx'),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['torre', 'numero'], name='splendore_v_torre_c9d00b_idx'),
        ),
    ]
