# Generated by Django 5.0.1 on 2025-07-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=5)),
                ('bloco', models.CharField(db_index=True, max_length=30)),
                ('pne', models.BooleanField(db_index=True, default=False)),
                ('vaga_coberta', models.BooleanField(db_index=True, default=False)),
                ('vaga_dupla', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['bloco', 'numero'], name='fatto_passi_bloco_2bb23d_idx'), models.Index(fields=['pne'], name='fatto_passi_pne_072f2b_idx'), models.Index(fields=['vaga_coberta'], name='fatto_passi_vaga_co_4e1382_idx'), models.Index(fields=['vaga_dupla'], name='fatto_passi_vaga_du_3b7f16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=80)),
                ('bloco', models.CharField(db_index=True, max_length=30)),
                ('pne', models.BooleanField(db_index=True, default=False)),
                ('vaga_coberta', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['bloco', 'numero'], name='fatto_passi_bloco_28576c_idx'), models.Index(fields=['pne'], name='fatto_passi_pne_d28b25_idx'), models.Index(fields=['vaga_coberta'], name='fatto_passi_vaga_co_f2a9cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatto_passion.apartamento')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatto_passion.vaga')),
            ],
            options={
                'indexes': [models.Index(fields=['apartamento', 'vaga'], name='fatto_passi_apartam_fed511_idx')],
            },
        ),
    ]
