# Generated by Django 5.0.1 on 2025-07-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatto_passion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='andar',
            field=models.CharField(choices=[('SUBSOLO_1', 'S1'), ('SUBSOLO_2', 'S2'), ('SUBSOLO_3', 'S3'), ('TERREO', 'Térreo')], db_index=True, default='TERREO', max_length=20),
        ),
        migrations.AddField(
            model_name='vaga',
            name='tamanho',
            field=models.CharField(choices=[('MEDIA', 'Média'), ('GRANDE', 'Grande')], db_index=True, default='MEDIA', max_length=10),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['andar'], name='fatto_passi_andar_fc3f67_idx'),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['tamanho'], name='fatto_passi_tamanho_8128ae_idx'),
        ),
    ]
