# Generated by Django 5.0.1 on 2025-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatto_passion', '0002_vaga_andar_vaga_tamanho_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apartamento',
            name='fatto_passi_vaga_du_3b7f16_idx',
        ),
        migrations.RemoveIndex(
            model_name='vaga',
            name='fatto_passi_bloco_28576c_idx',
        ),
        migrations.RemoveField(
            model_name='apartamento',
            name='vaga_dupla',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='bloco',
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['numero'], name='fatto_passi_numero_eed13c_idx'),
        ),
    ]
